# -*- coding: utf-8 -*-
{
    'name': "Product Lot Size",

    'summary': """
        This module allow a user to define the maximum manufacturing order lot size when
        the order is generated by the Reordering Rule Scheduler""",

    'description': """
        This module allow a user to define the maximum manufacturing order lot size when
        the order is generated by the Reordering Rule Scheduler
    """,

    'author': "Naing Lynn Htun",
    'website': "http://www.yourcompany.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'license': 'LGPL-3',
    'category': 'Manufacturing/Manufacturing',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['mrp','sale','sale_stock','sale_mrp','sale_order_type'],

    # always loaded
    'data': [
        # 'security/ir.model.access.csv',
        'views/product_views.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
}
